### ISSUE TITLE
Configuration injectable in manifests

### ISSUE THREAD

**Issue by ghost** [transfer-framework/bundle#7]

**Comment by valisj** [comment]
@htollefsen I think we can make this work by simply adding the configuration directly to the service definition:

```
services:
    manifest.test:
        class: AppBundle\Transfer\TestManifest
        arguments:
            - 
                option1: "value1"
                option2: 
                    option21: "value21"
                    option22: "value22"
        tags:
            - { name: transfer.manifest }
```

This will also work with manifests that are preconfigured:

```
services:
    manifest.test:
        parent: already_defined_and_configured_manifest_service
        arguments:
            - 
                option1: "value1"
                option2: 
                    option21: "value21"
                    option22: "value22"
```

The configuration can also be extracted and defined somewhere else:
```
parameters:
    manifest.test.configuration:
        option1: "value1"
        option2: 
            option21: "value21"
            option22: "value22"

services:
    manifest.test:
        parent: already_defined_and_configured_manifest_service
        arguments:
            - %manifest.test.configuration%
```

Thoughts?
